"""Edit workrecord

Revision ID: 03f88ee7271c
Revises: a5e149353494
Create Date: 2024-08-13 14:52:14.777772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f88ee7271c'
down_revision = 'a5e149353494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isWorking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('offSpecial', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('offRate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_record', schema=None) as batch_op:
        batch_op.drop_column('offRate')
        batch_op.drop_column('offSpecial')
        batch_op.drop_column('isWorking')

    # ### end Alembic commands ###
