"""add ngay nghi va ca lam viec

Revision ID: 08801fcdfe32
Revises: f50560955037
Create Date: 2024-08-29 09:09:15.786120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08801fcdfe32'
down_revision = 'f50560955037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NgayNghi', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Calamviec', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_sheet', schema=None) as batch_op:
        batch_op.drop_column('Calamviec')
        batch_op.drop_column('NgayNghi')

    # ### end Alembic commands ###
