"""Update worksheet

Revision ID: 16ab822465bd
Revises: fe0041d0e7a7
Create Date: 2024-08-12 16:44:25.527041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ab822465bd'
down_revision = 'fe0041d0e7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('workDate', sa.Date(), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('overTime', sa.Integer(), nullable=True),
    sa.Column('lateTime', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worksheet_id'], ['work_sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('SalaryName', sa.String(length=255), nullable=True),
    sa.Column('Salary', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worksheet_id'], ['work_sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_salary')
    op.drop_table('work_record')
    # ### end Alembic commands ###
