"""add zalo_avatar to Profile

Revision ID: 23e2f683c327
Revises: 03f88ee7271c
Create Date: 2024-08-15 09:56:03.574528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e2f683c327'
down_revision = '03f88ee7271c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zalo_avatar', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('zalo_avatar')

    # ### end Alembic commands ###
