"""update Work

Revision ID: 4e52352edebe
Revises: e6ebe46613fd
Create Date: 2024-08-16 15:51:52.002829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e52352edebe'
down_revision = 'e6ebe46613fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isMonthly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('checkedDate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_salary', schema=None) as batch_op:
        batch_op.drop_column('checkedDate')
        batch_op.drop_column('isMonthly')

    # ### end Alembic commands ###
