"""Update user profile

Revision ID: 500da2312d7b
Revises: c0ab26ae681e
Create Date: 2024-08-12 13:23:06.366576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500da2312d7b'
down_revision = 'c0ab26ae681e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('zalo_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('zalo_phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
        batch_op.alter_column('huyen',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('tinh',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('long_pos',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('lat_pos',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('lat_pos',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('long_pos',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('tinh',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('huyen',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('zalo_phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('zalo_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
