"""Add photo

Revision ID: 566a71830c5c
Revises: 16ab822465bd
Create Date: 2024-08-13 08:12:11.520208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566a71830c5c'
down_revision = '16ab822465bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.String(length=150), nullable=True),
    sa.Column('filesize', sa.String(length=150), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
