"""them option tinh vao tang ca hay khong

Revision ID: 9455d5c6d100
Revises: 08801fcdfe32
Create Date: 2024-08-29 10:08:09.304972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9455d5c6d100'
down_revision = '08801fcdfe32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isTangca', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_salary', schema=None) as batch_op:
        batch_op.drop_column('isTangca')

    # ### end Alembic commands ###
