"""add luong

Revision ID: b97389cd52b6
Revises: 4dc442ead406
Create Date: 2024-08-17 16:51:48.358902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97389cd52b6'
down_revision = '4dc442ead406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Giobinhthuong', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Giotangca', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Heso', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_record', schema=None) as batch_op:
        batch_op.drop_column('Heso')
        batch_op.drop_column('Giotangca')
        batch_op.drop_column('Giobinhthuong')

    # ### end Alembic commands ###
