"""Update user profile

Revision ID: c0ab26ae681e
Revises: 93976c335272
Create Date: 2024-08-12 12:56:31.617139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ab26ae681e'
down_revision = '93976c335272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zalo_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('zalo_phone', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=225), nullable=False))
        batch_op.add_column(sa.Column('huyen', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('tinh', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('long_pos', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('lat_pos', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('time_log', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('lat_pos')
        batch_op.drop_column('long_pos')
        batch_op.drop_column('tinh')
        batch_op.drop_column('huyen')
        batch_op.drop_column('address')
        batch_op.drop_column('full_name')
        batch_op.drop_column('zalo_phone')
        batch_op.drop_column('zalo_name')

    # ### end Alembic commands ###
