"""Add user photo

Revision ID: ccd9231dcfea
Revises: 566a71830c5c
Create Date: 2024-08-13 08:12:27.358302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd9231dcfea'
down_revision = '566a71830c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wallpaper_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_profile_wallpaper', 'photos', ['wallpaper_id'], ['id'])
        batch_op.create_foreign_key('fk_profile_avatar', 'photos', ['avatar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profile_avatar', type_='foreignkey')
        batch_op.drop_constraint('fk_profile_wallpaper', type_='foreignkey')
        batch_op.drop_column('wallpaper_id')
        batch_op.drop_column('avatar_id')

    # ### end Alembic commands ###
