"""add bonus

Revision ID: df25e257daaa
Revises: 31fb73209552
Create Date: 2024-09-07 14:44:46.442352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df25e257daaa'
down_revision = '31fb73209552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonusSalary', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_record', schema=None) as batch_op:
        batch_op.drop_column('bonusSalary')

    # ### end Alembic commands ###
