"""update WorkSalary

Revision ID: e6ebe46613fd
Revises: 23e2f683c327
Create Date: 2024-08-16 15:49:12.723738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ebe46613fd'
down_revision = '23e2f683c327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FinishWorkingDay', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('StartDate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_sheet', schema=None) as batch_op:
        batch_op.drop_column('StartDate')
        batch_op.drop_column('FinishWorkingDay')

    # ### end Alembic commands ###
